comercio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('core.urls')),   
    path('admin/', admin.site.urls),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
     path('',views.inbox, name='inbox'),
     path('<int:pk>/',views.detalles, name='detalles'),
    path('new/<int:item_pk>/', views.nueva_conver, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/',views.contact, name='contact'),
    path('signup/',views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login' )
]

dashboard/urls.py
from django.urls import path

from . import views

app_name= 'dashboard'

urlpatterns = [
    path('',views.index, name='index'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('<int:pk>/',views.indice_produc , name='indice_produc'),
    path('New_produc/',views.new_form ,name='new_form'),
    path('<int:pk>/eliminar/',views.eliminar, name='eliminar'),
    path('<int:pk>/modificar/',views.modificar, name='modificar'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
     username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Nombre del usuario',
        'class': 'w-full py-4 px-6 rounded-lx'
    }))
     password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Tu contrañesa',
        'class': 'w-full py-4 px-6 rounded-lx'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Nombre del usuario',
        'class': 'w-full py-4 px-6 rounded-lx'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Tu Email',
        'class': 'w-full py-4 px-6 rounded-lx'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Tu contrañesa',
        'class': 'w-full py-4 px-6 rounded-lx'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Repita contraseña',
        'class': 'w-full py-4 px-6 rounded-lx'
    }))

core/views.py
from django.shortcuts import render , redirect
from item.models import Categoria, Item
from .forms import SignupForm
# Create your views here.


def index(request):
    items= Item.objects.filter(se_vende=False)[0:6]
    categorias= Categoria.objects.all()
    return render (request,'core/index.html',{
        'categorias': categorias,
        'items': items,
    })

def contact(request):
    return render (request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form =SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect ('/login/')
        
    else:
        form= SignupForm ()
    return render( request,'core/signup.html',{
        'form': form,
    })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{%block title%} {%endblock%}Document</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items_center border-b border-gray-200">
        <a href="/"class='text-xl font-semibold'>Inicio ✔️</a>
        <div>
            <a href="{% url 'item:new_form'%}"class='text-xl font-semibold hover:text-gray-500'>Agregar Producto ✔️</a>
            <a href="{% url 'item:items' %}"class='text-xl font-semibold hover:text-gray-500'>Buscar 🕵🏼‍♂️</a>

            {% if request.user.is_authenticated %}
                
            <a href="{% url 'conversation:inbox' %}"class='px-6 py-3 text-lg font-semibold bg-teal-500 text-black rounded-xl hover:bg-teal-700'>Chat</a>
            <a href="{% url 'dashboard:index' %}"class='px-6 py-3 text-lg font-semibold bg-gray-500 text-black rounded-xl hover:bg-gray-700'>Mis productos ✔️</a>
       
            {% else %}
                <a href="{% url 'core:signup' %}"class='px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700'>Crear usuario</a>
                <a href="{% url 'core:login' %}"class='px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700'>Iniciar secion</a>
            {% endif%}
            
        </div>

    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {%endblock%}
    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-500">Abaut</h3>
            <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores </p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-500">Menu</h3>

            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Abaut</a></li>
            <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privasidad</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terminos de uso</a></li>
        </div>
    </footer>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}
{%block title%} contact {%endblock%}

{%block content%}

    <h1>Contactos</h1>

{%endblock%}

core/templates/core/index.html
{% extends 'core/base.html'%}

{%block title%} Bienvenidos {%endblock%}

{%block content%}

    <div class="mt_6 px-10 py-12 bg-blue-400 rounded-xl">
        <h1 class="mb-12 text-2xl text-center">Productos</h1>

        <div class="grid grid-cols-3 gap-3">
            {%for item in items%}
                <div>
                    <a href="{% url 'item:indice_produc' item.id %}">
                        <div>
                            <img src="{{item.imagen.url}}" class="rounded-t-xl">
                        </div>
                        
                        <div class="p-6 bg-white rounded-b-xl">

                            <h2 class="text-2xl">{{item.name}} </h2>
                            
                            <p class="texst-gray-500">Precio: {{item.precio}}</p>

                        </div>
                    </a>
                </div>
            {%endfor%}
        </div>
    </div>
    <div class="mt_6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 texst-2xl text-center">Categorias</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for categoria in categorias %}
                <div>
                    <a href="#">
                        
                        <div class="p-6 bg-white rounded-b-xl">

                            <h2 class="text-2xl">{{categoria.name}} </h2>
                            <p class="texst-gray-500">{{categoria.items.count }} items</p>

                        </div>
                    </a>
                </div>
            {%endfor%}
        </div>
{%endblock%}

core/templates/core/login.html
{% extends 'core/base.html' %}
{%block title%} Crea User {% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl"> Usuario </h1>
        <form method="POST" , action=".">
            {% csrf_token %}
           
            <div class="mb-3">
                <label  class="inline-block mb-2" >Usuario</label><br>
                {{ form.username}}
            </div>
            
            <div class="mb-3">
                <label  class="inline-block mb-2" >Password</label><br>
                {{ form.password}}
            </div>
            
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{field.errors}}
                    {%endfor%}
                    {{form.non_field_errors}}
                </div>
            {%endif%}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Ingresar</button>
        </form>
    </div>
{%endblock%}

core/templates/core/signup.html
{% extends 'core/base.html' %}
{%block title%} Crea User {% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl"> Usuario </h1>
        <form method="POST" , action=".">
            {% csrf_token %}
           
            <div class="mb-3">
                <label  class="inline-block mb-2" >Usuario</label><br>
                {{ form.username}}
            </div>
            <div class="mb-3">
                <label  class="inline-block mb-2" >Email</label><br>
                {{ form.email}}
            </div>
            <div class="mb-3">
                <label  class="inline-block mb-2" >Password</label><br>
                {{ form.password1}}
            </div>
            <div class="mb-3">
                <label  class="inline-block mb-2" >Repita Password</label><br>
                {{ form.password2}}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{field.errors}}
                    {%endfor%}
                    {{form.non_field_errors}}
                </div>
            {%endif%}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Ingresar</button>
        </form>
    </div>
{%endblock%}