comercio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('core.urls')),   
    path('admin/', admin.site.urls),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
     path('',views.inbox, name='inbox'),
     path('<int:pk>/',views.detalles, name='detalles'),
    path('new/<int:item_pk>/', views.nueva_conver, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/',views.contact, name='contact'),
    path('signup/',views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login' )
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('<int:pk>/',views.indice_produc , name='indice_produc'),
    path('New_produc/',views.new_form ,name='new_form'),
    path('<int:pk>/eliminar/',views.eliminar, name='eliminar'),
    path('<int:pk>/modificar/',views.modificar, name='modificar'),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Categoria(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        ordering = ('name' ,)
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name
    

class Item(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='items',on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    decripcion= models.TextField(blank=True, null=True)
    precio = models.FloatField()
    imagen = models.ImageField(upload_to='item_imagen', blank=True, null= True)
    se_vende = models.BooleanField(default=False)
    creado_por = models.ForeignKey(User, related_name='Item', on_delete=models.CASCADE)
    crea_proc = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class Nuevo_produc(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('categoria','name','decripcion','precio','imagen',)
        widgets = {
            'categoria': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
             'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
              'decripcion': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
             'precio': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
             'imagen':forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class Edit_form(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name','decripcion','precio','imagen','se_vende')
        widgets = {
            
             'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
              'decripcion': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
             'precio': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
             'imagen':forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
            
        }

item/views.py
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404 , redirect
from .models import Item, Categoria
from .forms import Nuevo_produc , Edit_form


def indice_produc(request, pk):
    item =get_object_or_404(Item, pk = pk)
    elementos_relacionados=Item.objects.filter(categoria=item.categoria, se_vende=False).exclude(pk=pk)[0:3]
    return render(request, 'item/indice_produc.html',{
        'item': item,
        'elementos_relacionados':elementos_relacionados
    })
# Create your views here.

def items(request):
    query = request.GET.get('query')
    categoria_id = request.GET.get('categoria',0)
    items= Item.objects.filter(se_vende= False,)
    categogias= Categoria.objects.all()

    if categoria_id:
        items = items.filter(categoria_id=categoria_id)

    if query:
        items= items.filter(Q(name__icontains=query) | Q (decripcion__icontains=query))
    return render( request, 'item/items.html',{
        'items': items,
        'query':query,
        'categorias':categogias,
        'categoria_id': int(categoria_id)
    })
#en lo de name_icontains hace que la peticion no sea sencible  a lo pedido en la buqueda 
# "Q" hace q sea mas facil en mulltiples campos

@login_required
def new_form(request):
    if request.method == "POST":
        form= Nuevo_produc(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.creado_por = request.user
            item.save()

            return redirect('item:indice_produc', pk=item.id)
    else:
        form = Nuevo_produc()
    return render(request, 'item/New_Produ.html',{
        'form':form,
        'title': 'Nuevo Producto'
    })

# En el inicio requiero iniciar sesion para poder eliminar necesito poner
# el decorardor que hacer referencia al inicio de sesion
#una vez terminado el producto lo redirecionamos a la lista de productos

@login_required
def eliminar(request, pk ):
    item = get_object_or_404 (Item, pk=pk, creado_por= request.user)
    item.delete()

    return redirect('dashboard:index')
# En esta funcion llamamos al decorador para verificar si es el usuario el del prodcuto lo q hacemos es buscar
# el obejeto que queremos modificar 

@login_required
def modificar(request,pk):
    item = get_object_or_404 (Item, pk=pk, creado_por= request.user)

    if request.method == "POST":
        form= Edit_form(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:indice_produc', pk=item.id)
    else:
        form = Edit_form(instance=item)
    return render(request, 'item/New_Produ.html',{
        'form':form,
        'title': 'Modificar Producto'
    })

item/templates/item/New_Produ.html
{% extends 'core/base.html' %}
{%block title%} {{title}} {%endblock%}

{%block content%}

<div class="mb-6 text-3xl">{{title}}</div>
<form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="space-y-4">
        {{form.as_p}}
        {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{field.errors}}
                    {%endfor%}
                    {{form.non_field_errors}}
                </div>
        {%endif%}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Cargar</button>
    </div>          
</form>
{%endblock%}

item/templates/item/indice_produc.html
{% extends 'core/base.html' %}

{%block title%} {{item.name}} {%endblock%}

{%block content%}

<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{item.imagen.url}}" class="rounded-b-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{item.name}}</h1>
        <p class="mb-6 texst-gray-500"> <strong>Precio: </strong> {{item.precio}}</p>
        <p class="mb-6 texst-gray-500"> <strong>Usuario: </strong> {{item.creado_por.username}}</p>
        
        {% if item.decripcion %}
            <p class="mb-6 texst-gray-700">
                <strong class="mb-6 texst-gray-500">Descripcion:</strong><br>
                {{item.decripcion}}</p>
        {%endif%}


        {%if request.user == item.creado_por  %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>Esto es su elemento</p>
                <a href="{% url 'item:modificar' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Modificar</a>
                <a href="{% url 'item:eliminar' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Eliminar</a>
            </div>
        {%else%}
            <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contatar al Vendedor</a>
        {%endif%}
    </div>


</div>
<div class="mt_6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 texst-2xl text-center">Elementos_relacionados</h2>

    <div class="grid grid-cols-3 gap-3">
        {%for item in elementos_relacionados%}
            <div>
                <a href="{% url 'item:indice_produc' item.id %}">
                    <div>
                        <img src="{{item.imagen.url}}" class="rounded-t-xl">
                    </div>
                    
                    <div class="p-6 bg-white rounded-b-xl">

                        <h2 class="text-2xl">{{item.name}} </h2>
                        <p class="texst-gray-500">Precio: {{item.precio}}</p>

                    </div>
                </a>
            </div>
        {%endfor%}
    </div>
</div>

{%endblock%}

item/templates/item/items.html
{% extends 'core/base.html' %}

{%block title%} Busqueda {%endblock%}

{%block content%}
    <div class="pb-6 grid grid-cols-4 gap-4">
        <div class="col-spaj-1">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{query}}" placeholder="Buscar 🧑🏻‍🍳">
                
                <button class="mt_2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Busqueda</button>
            
            </form>
            <hr class="my-6">

            <p class="font-semibold"> Categorias </p>
            <ul>
                {% for categoria in categorias %}
                    <li class="py-2 px-6 rounded-xl {%if categoria.id == categoria_id%} bg-gray-200 {%endif%}">
                        <a href="{% url 'item:items' %}?query = {{query}}&categoria={{categoria.id}}">{{categoria.name}}</a>
                    </li>
                
                {% endfor %}
            </ul>
            <hr class="my-6">

            <p class="font-semibold"> Borrar Busqueda </p>
            <ul>
                <li><a href="{% url 'item:items'%} " class="mt-2 py-4 px-8 inline-block bg-red-700 text-lg rounded-xl text-white" >🗑️</a>
                </li>
            </ul>

        </div>
        <div class=" col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {%for item in items%}
                    <div>
                        <a href="{% url 'item:indice_produc' item.id %}">
                            <div>
                                    <img src="{{item.imagen.url}}" class="rounded-t-xl">
                            </div>
                                
                            <div class="p-6 bg-white rounded-b-xl">
        
                                    <h2 class="text-2xl">{{item.name}} </h2>
                                    
                                    <p class="texst-gray-500">Precio: {{item.precio}}</p>
        
                            </div>
                        </a>
                    </div>
                {%endfor%}
            </div>
        </div>
    </div>

{%endblock%}